<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Activities extends MY_Controller {

    // protected $access = array('Admin', 'Pimpinan','Finance');
    
    function __construct()
    {
        parent::__construct();
        $this->load->model('Activities_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'activities/index.dart?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'activities/index.dart?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'activities/index.dart';
            $config['first_url'] = base_url() . 'activities/index.dart';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Activities_model->total_rows($q);
        $activities = $this->Activities_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'activities_data' => $activities,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('header');
        $this->load->view('activities_list', $data);
        $this->load->view('footer');
    }

    public function read($id) 
    {
        $row = $this->Activities_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'aktivitas' => $row->aktivitas,
	    );
            $this->load->view('header');
            $this->load->view('activities_read', $data);
            $this->load->view('footer');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('activities'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('activities/create_action'),
	    'id' => set_value('id'),
	    'aktivitas' => set_value('aktivitas'),
	);

        $this->load->view('header');
        $this->load->view('activities_form', $data);
        $this->load->view('footer');
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'aktivitas' => $this->input->post('aktivitas',TRUE),
	    );

            $this->Activities_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('activities'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Activities_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('activities/update_action'),
		'id' => set_value('id', $row->id),
		'aktivitas' => set_value('aktivitas', $row->aktivitas),
	    );
            $this->load->view('header');
            $this->load->view('activities_form', $data);
            $this->load->view('footer');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('activities'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'aktivitas' => $this->input->post('aktivitas',TRUE),
	    );

            $this->Activities_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('activities'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Activities_model->get_by_id($id);

        if ($row) {
            $this->Activities_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('activities'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('activities'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('aktivitas', 'aktivitas', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Activities.php */
/* Location: ./application/controllers/Activities.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-26 09:56:38 */
/* http://harviacode.com */